### ISSUE TITLE
Should this repo get renamed google-cloud-common ??

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-common#206]
@jgeewax 
@broady 

Seems like we are renaming core things.

**Comment by broady** [comment]
Maybe the name is too generic, then.

`google-cloud-clients-common`?

**Comment by stephenplusplus** [comment]
👍 to `clients` or something similar in the name, to avoid general GCP questions & confusion between the client libs and the SDK.

**Comment by blowmage** [comment]
Bump.

**Comment by tswast** [comment]
How about `google-cloud-client-libraries-common`? It's a bit long, but it's unambiguous.

**Comment by garrettjonesgoogle** [comment]
What is the purpose of this repo? It doesn't seem to contain code... why are we using github?

**Comment by tswast** [comment]
Looks like docs about general things related to client libraries. I don't know who owns it. Maybe some of this would be better suited on cloud.google.com?

**Comment by quartzmo** [comment]
It does contain code, for the Angular-based [documentation site](https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/site) used by google-cloud-node, google-cloud-ruby, and possibly others.

**Comment by garrettjonesgoogle** [comment]
Is there any code besides the Angular-based documentation site?

**Comment by blowmage** [comment]
We have used this repo to publicly discuss Google Cloud issues across the various language clients. Shared topics such as design, documentation, naming, etc. That is why it is postfixed with "common".

The various language clients all changed their names from gcloud-_language_ to google-cloud-_language_, but this repo was not changed.

**Comment by quartzmo** [comment]
@garrettjonesgoogle I believe the Angular-based documentation site is the only code in the repo.

**Comment by tswast** [comment]
Since this repo is going to hang around, at least for some amount of time. Let's do the rename.

Shall I do it? How did `google-cloud-client-libraries-common` sound?

**Comment by garrettjonesgoogle** [comment]
If `gcloud-common` worked fine before... why not `google-cloud-common` now? Don't we want to avoid really long names?

**Comment by quartzmo** [comment]
`google-cloud-meta`? Just throwing it out there...

**Comment by tswast** [comment]
Alright. `google-cloud-common` it is. If folks get confused and start filing all sorts of miscellaneous issues we can lock it down and/or rename.

**Comment by tswast** [comment]
Renamed. Looks like the readme still needs an update.
