### ISSUE TITLE
Add "table of contents" for the landing pages with lots of content?

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-common#221]
*[Originally reported in GCN](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2110) by @jgeewax*

---

Pages like the Datastore landing page (https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/datastore) have a ton of useful content, but there's no quick way to navigate to each section (e.g., "I forgot how to do transactional stuff... I just want a reminder about those transaction things").

Can we add a TOC-type box (maybe like the one that shows the available methods) for these pages? For example (I could just click "Transactions" in the box)

![image](https://cloud.githubusercontent.com/assets/112928/24099359/1bc59012-0d45-11e7-8088-2982519b920f.png)

(Though we may want to change some of the headings now that they're front-and-center).

**Comment by stephenplusplus** [comment]
*can be closed*

**Comment by callmehiphop** [comment]
Closing as this is no longer relevant!
