### ISSUE TITLE
ci: build failures

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-common#228]
Travis appears to be unhappy with us :(

https://travis-ci.org/GoogleCloudPlatform/gcloud-common/builds/257084054?utm_source=github_status&utm_medium=notification

**Comment by JustinBeckwith** [comment]
@callmehiphop is this still relevant?

**Comment by callmehiphop** [comment]
I don't think so, assuming Ruby has moved away from the old docs site, I don't think we have a need to run anything here on CI.
