### ISSUE TITLE
Storage pubsub notifications: whitelist needed?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-common#231]
While working on sytem tests for the [bucket notification feature for Python](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/3956-storage-notifications), I'm seeing 403 errors during the `notificaitions/insert` API call:

```python
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/tests/system.py", line 608, in test_notification_minimal
    retry_429(notification.create)()
  File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/.nox/sys-3-6/lib/python3.6/site-packages/test_utils/retry.py", line 95, in wrapped_function
    return to_wrap(*args, **kwargs)
  File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/google/cloud/storage/notification.py", line 243, in create
    data=properties,
  File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/.nox/sys-3-6/lib/python3.6/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api.core.exceptions.Forbidden: 403 POST https://www.googleapis.com/storage/v1/b/notification-minimal-1506015899035/notificationConfigs: The service account 'precise-truck-742@gs-project-accounts.iam.gserviceaccount.com' does not have permission to publish messages to to the Cloud Pub/Sub topic '//pubsub.googleapis.com/projects/precise-truck-742/topics/notification-1506015836204', or that topic does not exist.
```

I have [verified](https://gist.github.com/tseaver/1944a34a187a5308fe4ce9fa6a146dd7) that a) the topic exists, and b) my credentials have all permissions for it.  Is the feature one of the "must be whitelisted" ones?

@dwsupplee, @quartzmo, @stephenplusplus  I know you have been working on the feature in your languages.  Do you have system tests passing yet?

**Comment by quartzmo** [comment]
@tseaver I'm so glad you raised this because I am experiencing exactly the same thing and have not found a solution for it.

```sh
irb(main):007:0> topic = pubsub.create_topic "storage_1"
=> #<Google::Cloud::Pubsub::Topic:0x007ffab684a270 @service=Google::Cloud::Pubsub::Service(bustling-kayak-91516), @grpc=<Google::Pubsub::V1::Topic: name: "projects/bustling-kayak-91516/topics/storage_1">, @lazy=nil, @exists=nil, @async_opts={}>
irb(main):008:0> bucket.create_notification topic.name
Google::Cloud::PermissionDeniedError: forbidden: The service account 'bustling-kayak-91516@gs-project-accounts.iam.gserviceaccount.com' does not have permission to publish messages to to the Cloud Pub/Sub topic '//pubsub.googleapis.com/projects/bustling-kayak-91516/topics/storage_1', or that topic does not exist.
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:441:in `rescue in execute'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:439:in `execute'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:218:in `insert_notification'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/bucket.rb:1146:in `create_notification'
	from (irb):8
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud/Rakefile:59:in `block in 
```

**Comment by dwsupplee** [comment]
I expected providing publish permissions to the topic using the `client_email` in the keyfile associated with the tests to work - but ran into similar issues.

When matching the format for the email found in the error message (`project-id@gs-project-accounts.iam.gserviceaccount.com`) the permissions worked correctly. You can access correctly formatted email from the following URI:

`https://www.googleapis.com/storage/v1/projects/[YOUR_PROJECT_NAME]/serviceAccount`

**Comment by tseaver** [comment]
@dwsupplee Ugh!

@lukesneeringer I don't understand how this stuff is supposed to work.  The credentials in my environment are valid to create the topic, create the bucket, but not to add a notification?  Can you get somebody on the back-end to work with us?

**Comment by tseaver** [comment]
@dwsupplee Thanks for the pointer!  I have [updated the system tests](https://github.com/GoogleCloudPlatform/google-cloud-python/commit/7d9ee947bdd3574490fbaa01f4228113f62367e6), adding IAM policy bindings which allow the "back-end" service account to publish to the topic, e.g.:

```python
@@ -567,14 +567,26 @@ class TestStorageNotificationCRUD(unittest.TestCase):
         return 'projects/{}/topics/{}'.format(
             Config.CLIENT.project, self.TOPIC_NAME)
 
-    def setUp(self):
-        self.case_buckets_to_delete = []
+    def _intialize_topic(self):
         try:
             from google.cloud.pubsub_v1 import PublisherClient
         except ImportError:
             raise unittest.SkipTest("Cannot import pubsub")
         self.publisher_client = PublisherClient()
         retry_429(self.publisher_client.create_topic)(self.topic_path)
+        policy = self.publisher_client.get_iam_policy(self.topic_path)
+        binding = policy.bindings.add()
+        binding.role = 'roles/pubsub.publisher'
+        binding.members.append(
+            'serviceAccount:{}'
+            '@gs-project-accounts.iam.gserviceaccount.com'.format(
+                Config.CLIENT.project))
+        self.publisher_client.set_iam_policy(self.topic_path, policy)
+
+
+    def setUp(self):
+        self.case_buckets_to_delete = []
+        self._intialize_topic()
```

@quartzmo I hope that example helps!

**Comment by BrandonY** [comment]
Yep, sorry for the confusion.

You, the user, need permission to modify the bucket's metadata and create pub/sub topics and such.

Separately, GCS needs your permission to publish to your Pub/Sub topic later. It does not publish as you but on its own, so you need to grant permission to it.

**Comment by BrandonY** [comment]
I'm hoping that the client libraries will take care of that detail for callers so that they will not all need to repeat that journey of discovery.

**Comment by quartzmo** [comment]
This is off-topic, but has anyone else seen this `insert` error? I get it even when `list` returns an empty collection.

```
invalid: Overlapping notification configurations. New notification prefix and event types overlap with existing notification config '1' with prefix (all).
```

**Comment by quartzmo** [comment]
I guess somehow the test is making a second attempt to create the same notification.

**Comment by tseaver** [comment]
@quartzmo Maybe eventual consistency is in play? I.e., `list` is being served from a host which doesn't have the notification yet?

**Comment by quartzmo** [comment]
@tseaver Yes, I'm going to assume the mistake must be on my end. I'll post if I discover anything interesting.

**Comment by BrandonY** [comment]
The only eventual consistency issue would be around sending notifications. There are no eventual consistency issues with inserting new subscriptions or requesting the current list of subscriptions.

One potential issue I've seen before is if the first call to create a notification subscription times out or returns a 500, the test might be set to retry automatically. In that case, it's possible the first call DID succeed, and the retry will try to create a new notification subscription, which will fail because they'd be overlapping.

**Comment by quartzmo** [comment]
@BrandonY Yes, my mistake, it was definitely a case of an extra attempt to insert the notification.

**Comment by quartzmo** [comment]
@tseaver OK to close this issue?
