### ISSUE TITLE
Storage Json API docs question

### ISSUE THREAD

**Issue by dwsupplee** [GoogleCloudPlatform/google-cloud-common#51]
https://cloud.google.com/storage/docs/json_api/v1/objects/patch

The projection property's description reads:

`Set of properties to return. Defaults to no_acl.`

I believe this should be camel case `noAcl` and it seems to cause the API to return ACL details when projection isn't explicitly defined.

Does anyone know if this intended or an issue that needs to be addressed?

/cc @jgeewax

**Comment by tseaver** [comment]
This repository is for the Python wrappers for Google Cloud APIs, and isn't the best place to report issues with the actual Cloud Storage API or its docs.  I'm not sure where such reports should be made.

**Comment by stephenplusplus** [comment]
This is a good point; we could use a good channel to report API bugs directly to who should see it, preferably in the open. This is the best we have for now, afaik.

Oh yeah, we have this tag: @GoogleCloudPlatform/cloud-storage
